import { CeramicMaterialPreset } from '../types';

export const CURATED_CERAMIC_MATERIALS: CeramicMaterialPreset[] = [
  {
    id: 'calacatta-oro-inlay',
    name: 'Calacatta Oro & Brass',
    category: 'marble',
    description: 'Italian Calacatta Oro porcelain with polished 24k brass geometric waterjet inlay veins.',
    glaze_type: 'gloss',
    finish: {
      roughness: 0.08,
      metallic: 0.12,
      glaze_type: 'gloss',
      luster_sheen: 0.9,
      subsurface_scatter: 0.35,
      bump_intensity: 0.4,
    },
    primary_hex: '#F6F6F2',
    secondary_hex: '#D4AF37',
    accent_hex: '#8C857B',
    pantone_code: 'PANTONE 11-0601 TCX',
    pigments: ['Alumina Silicate Frit', 'Zirconium Opacifier', 'Micronized Brass Alloy'],
    recommended_archetype: 'countertop_slab',
    firing_temp_celsius: 1220,
    slip_resistance_rating: 'R9 / PTV 28',
    ai_prompt: 'Italian Calacatta Oro porcelain with warm golden veins, polished mirror vitrified glaze and brushed brass geometric inlays',
    tags: ['Luxury', 'Vitrified', 'Brass Inlay', 'Slab', 'Kitchen Island'],
  },
  {
    id: 'carrara-statuario-honed',
    name: 'Carrara Statuario Honed',
    category: 'marble',
    description: 'Classic Tuscan Statuario marble porcelain in soft silk honed finish with delicate grey feathers.',
    glaze_type: 'satin',
    finish: {
      roughness: 0.28,
      metallic: 0.02,
      glaze_type: 'satin',
      luster_sheen: 0.45,
      subsurface_scatter: 0.28,
      bump_intensity: 0.3,
    },
    primary_hex: '#EDEDEB',
    secondary_hex: '#6B7280',
    accent_hex: '#D1D5DB',
    pantone_code: 'PANTONE 12-4301 TCX',
    pigments: ['Carrara Marble Micron Powder', 'Silica Matting Agent'],
    recommended_archetype: 'stair_tread',
    firing_temp_celsius: 1210,
    slip_resistance_rating: 'R10 / PTV 38+',
    ai_prompt: 'Carrara Statuario marble porcelain in honed satin finish with fine charcoal dendrite veining',
    tags: ['Honed', 'Stairs', 'Anti-Slip R10', 'Architectural'],
  },
  {
    id: 'nero-marquina-mirror',
    name: 'Nero Marquina Vitrified',
    category: 'marble',
    description: 'Deep obsidian black Spanish porcelain with crisp crystalline white calcite lightning veins.',
    glaze_type: 'gloss',
    finish: {
      roughness: 0.05,
      metallic: 0.04,
      glaze_type: 'gloss',
      luster_sheen: 0.95,
      subsurface_scatter: 0.1,
      bump_intensity: 0.2,
    },
    primary_hex: '#111215',
    secondary_hex: '#F9FAFB',
    accent_hex: '#374151',
    pantone_code: 'PANTONE 19-4005 TCX',
    pigments: ['Cobalt-Iron Black Spinel', 'Pure Quartz Frit'],
    recommended_archetype: 'countertop_slab',
    firing_temp_celsius: 1235,
    slip_resistance_rating: 'R9 / PTV 26',
    ai_prompt: 'High-gloss Spanish Nero Marquina porcelain with intense black background and stark white calcite fractures',
    tags: ['High Contrast', 'Minimalist', 'Waterfall Miter'],
  },
  {
    id: 'cobalt-majolica-relief',
    name: 'Cobalt Majolica Luster',
    category: 'majolica',
    description: 'Handcrafted Mediterranean Majolica glaze with deep cobalt blues, micro-crackle, and 3D bas-relief sheen.',
    glaze_type: 'luster',
    finish: {
      roughness: 0.16,
      metallic: 0.32,
      glaze_type: 'luster',
      luster_sheen: 0.88,
      subsurface_scatter: 0.45,
      bump_intensity: 0.85,
    },
    primary_hex: '#1B365D',
    secondary_hex: '#F8FAFC',
    accent_hex: '#00F0FF',
    pantone_code: 'PANTONE 19-3952 TCX',
    pigments: ['Cobalt Aluminate Blue Spinel', 'Tin Oxide Opacifier', 'Bismuth Luster'],
    recommended_archetype: '3d_wall_panel',
    firing_temp_celsius: 1060,
    slip_resistance_rating: 'R9',
    ai_prompt: 'Cobalt Blue Mediterranean Majolica glaze with bas-relief carved panels and micro-crackle luster sheen',
    tags: ['Artisanal', 'Relief Cladding', 'Crackle', 'Luster'],
  },
  {
    id: 'emerald-majolica-crackle',
    name: 'Venetian Emerald Majolica',
    category: 'majolica',
    description: 'Luminous emerald copper glaze with soft vitreous depth and handcrafted undulating relief texture.',
    glaze_type: 'luster',
    finish: {
      roughness: 0.14,
      metallic: 0.28,
      glaze_type: 'luster',
      luster_sheen: 0.85,
      subsurface_scatter: 0.5,
      bump_intensity: 0.75,
    },
    primary_hex: '#0E4D3E',
    secondary_hex: '#D4AF37',
    accent_hex: '#A7F3D0',
    pantone_code: 'PANTONE 19-5420 TCX',
    pigments: ['Copper Carbonate Green', 'Titanium Dioxide', 'Lead-Free Borosilicate'],
    recommended_archetype: '3d_wall_panel',
    firing_temp_celsius: 1080,
    slip_resistance_rating: 'R9',
    ai_prompt: 'Venetian Emerald green handcrafted tile with copper glaze and subtle molten relief details',
    tags: ['Artisanal', 'Jewel Tone', '3D Wall Panel'],
  },
  {
    id: 'volcanic-basalt-fluted',
    name: 'Volcanic Basalt Fluted',
    category: 'stone',
    description: 'Porous charcoal volcanic basalt stone with micro-fluted vertical grooves and ultra-matte tactility.',
    glaze_type: 'matte',
    finish: {
      roughness: 0.82,
      metallic: 0.02,
      glaze_type: 'matte',
      luster_sheen: 0.08,
      subsurface_scatter: 0.05,
      bump_intensity: 1.2,
    },
    primary_hex: '#232326',
    secondary_hex: '#52525B',
    accent_hex: '#71717A',
    pantone_code: 'PANTONE 19-0201 TCX',
    pigments: ['Volcanic Ash Aggregate', 'Magnetite Mineral'],
    recommended_archetype: '3d_wall_panel',
    firing_temp_celsius: 1250,
    slip_resistance_rating: 'R11 / PTV 45+ (High Wet Grip)',
    ai_prompt: 'Matte dark volcanic basalt ceramic with vertical fluted grooves and rough volcanic texture',
    tags: ['Ultra Matte', 'Fluted', 'Exterior', 'High Slip Resistance'],
  },
  {
    id: 'travertine-navona-satin',
    name: 'Travertine Navona Cross-Cut',
    category: 'stone',
    description: 'Roman Travertine with horizontal sedimentary travertine bands in warm ivory and filled pore satin finish.',
    glaze_type: 'satin',
    finish: {
      roughness: 0.38,
      metallic: 0.03,
      glaze_type: 'satin',
      luster_sheen: 0.3,
      subsurface_scatter: 0.32,
      bump_intensity: 0.6,
    },
    primary_hex: '#E7DFCF',
    secondary_hex: '#B8A88E',
    accent_hex: '#8C7853',
    pantone_code: 'PANTONE 13-0908 TCX',
    pigments: ['Limestone Powder', 'Iron Oxide Ochre Frit'],
    recommended_archetype: 'stair_tread',
    firing_temp_celsius: 1200,
    slip_resistance_rating: 'R10 / PTV 36',
    ai_prompt: 'Roman Travertine Navona stone porcelain in cross-cut satin texture with gentle banded striations',
    tags: ['Warm Neutral', 'Classic', 'Stair Nosing'],
  },
  {
    id: 'venetian-terrazzo-bronze',
    name: 'Venetian Emerald Terrazzo',
    category: 'terrazzo',
    description: 'Precast Venetian Terrazzo with green alpine river stones, Carrara marble chips, and cast bronze divider inlays.',
    glaze_type: 'satin',
    finish: {
      roughness: 0.25,
      metallic: 0.18,
      glaze_type: 'satin',
      luster_sheen: 0.6,
      subsurface_scatter: 0.3,
      bump_intensity: 0.45,
    },
    primary_hex: '#1E3A2F',
    secondary_hex: '#C5A059',
    accent_hex: '#E5E7EB',
    pantone_code: 'PANTONE 19-5511 TCX',
    pigments: ['Verde Alpi Aggregate', 'Carrara Marble Chips', 'Bronze Dust Inlay'],
    recommended_archetype: 'flat_tile',
    firing_temp_celsius: 1210,
    slip_resistance_rating: 'R10 / PTV 36',
    ai_prompt: 'Venetian Emerald Terrazzo with multi-scale stone aggregates and embedded bronze metal inlay lines',
    tags: ['Terrazzo', 'Bronze Inlay', 'Mid-Century'],
  },
  {
    id: 'corten-oxide-ceramic',
    name: 'Corten Steel Ceramic',
    category: 'metal_oxide',
    description: 'Weathered corten oxide ceramic with iridescent copper-rust undertones and industrial patinated sheen.',
    glaze_type: 'luster',
    finish: {
      roughness: 0.44,
      metallic: 0.62,
      glaze_type: 'luster',
      luster_sheen: 0.72,
      subsurface_scatter: 0.12,
      bump_intensity: 0.9,
    },
    primary_hex: '#6B3A23',
    secondary_hex: '#C86D3B',
    accent_hex: '#2B1A12',
    pantone_code: 'PANTONE 18-1248 TCX',
    pigments: ['Iron Oxide Red', 'Manganese Dioxide', 'Copper Luster Frit'],
    recommended_archetype: '3d_wall_panel',
    firing_temp_celsius: 1225,
    slip_resistance_rating: 'R10',
    ai_prompt: 'Oxidized corten steel metallic ceramic panel with weathered patina and rust sheen',
    tags: ['Industrial', 'Oxide', 'Metallic Sheen', 'Cladding'],
  },
  {
    id: 'tuscan-cotto-impruneta',
    name: 'Tuscan Cotto Impruneta',
    category: 'terracotta',
    description: 'Hand-extruded Tuscan terracotta made from Impruneta clay with natural earth variation and raw tactile porosity.',
    glaze_type: 'matte',
    finish: {
      roughness: 0.85,
      metallic: 0.0,
      glaze_type: 'matte',
      luster_sheen: 0.05,
      subsurface_scatter: 0.38,
      bump_intensity: 1.1,
    },
    primary_hex: '#B25338',
    secondary_hex: '#8C3820',
    accent_hex: '#E8A588',
    pantone_code: 'PANTONE 18-1442 TCX',
    pigments: ['Natural Impruneta Red Clay', 'Sienna Mineral'],
    recommended_archetype: 'skirting_molding',
    firing_temp_celsius: 1020,
    slip_resistance_rating: 'R11 / PTV 42+',
    ai_prompt: 'Authentic Tuscan hand-made terracotta cotto tile in warm terracotta clay with organic rustic surface texture',
    tags: ['Warm Earth', 'Handmade', 'Terracotta', 'Molding'],
  },
  {
    id: 'skirting-modern-shadowline',
    name: 'Shadowline Minimalist Trim',
    category: 'stone',
    description: 'Sleek architectural porcelain skirting with a recessed 5mm shadowline groove for flush dry-wall detailing.',
    glaze_type: 'satin',
    finish: {
      roughness: 0.32,
      metallic: 0.05,
      glaze_type: 'satin',
      luster_sheen: 0.35,
      subsurface_scatter: 0.2,
      bump_intensity: 0.25,
    },
    primary_hex: '#E2E2DF',
    secondary_hex: '#1E1E20',
    accent_hex: '#9CA3AF',
    pantone_code: 'PANTONE 14-4102 TCX',
    pigments: ['Alumina Silicate Body', 'Fine Satin Glaze'],
    recommended_archetype: 'skirting_molding',
    firing_temp_celsius: 1215,
    slip_resistance_rating: 'R9',
    ai_prompt: 'Modern architectural skirting profile with crisp 45 degree miter cut and 5mm recessed shadowline groove',
    tags: ['Skirting', 'Trim', 'Shadowline', 'Minimalist'],
  },
  {
    id: 'arabescato-orobico-slab',
    name: 'Arabescato Orobico Sintered',
    category: 'marble',
    description: 'Dramatic Italian marble with swirling charcoal, bronze, and dove grey sedimentary currents for bookmatched islands.',
    glaze_type: 'gloss',
    finish: {
      roughness: 0.07,
      metallic: 0.1,
      glaze_type: 'gloss',
      luster_sheen: 0.92,
      subsurface_scatter: 0.3,
      bump_intensity: 0.35,
    },
    primary_hex: '#4A4C50',
    secondary_hex: '#C5A059',
    accent_hex: '#E5E7EB',
    pantone_code: 'PANTONE 18-5203 TCX',
    pigments: ['Grey Carbonaceous Spinel', 'Ochre Inlay Frit', 'Super-Vitrified Enamel'],
    recommended_archetype: 'countertop_slab',
    firing_temp_celsius: 1240,
    slip_resistance_rating: 'R9 / PTV 27',
    ai_prompt: 'Arabescato Orobico jumbo porcelain slab with dynamic swirling grey and gold veins for continuous waterfall miter edge',
    tags: ['Bookmatch', 'Dramatic Veins', 'Waterfall Island', '3200mm Slab'],
  },
];
