import { create } from 'zustand';
import { Dimensions, FinishProps, ColorData, ReferenceAssets, ProductionMode, VectorPath, ObjectTransform, CAMQualityReport, MaterialCalculations, FactoryPassport, AgentStepLog, ArchitecturalArchetype, StairTreadParams, WallPanel3DParams, SkirtingMoldingParams, CountertopSlabParams } from '../types';
import { DEFAULT_LAYERS, ProjectLayer } from '../types/project';
import { ObjectTransform3D, SceneObject, MaterialDefinition, ProjectV2, SceneV2, IDENTITY_TRANSFORM_3D } from '../types/scene';
import { calculateMaterialMetrics, runCAMQualityCheck, hexToCmyk, findClosestPantone } from '../utils/cadMath';
import { DEFAULT_STAIR_PARAMS, DEFAULT_WALL_PANEL_PARAMS, DEFAULT_MOLDING_PARAMS, DEFAULT_SLAB_PARAMS } from '../services/archetypeClientService';
import { buildManufacturingPlan, ManufacturingPlan } from '../services/manufacturingEngine';
import { auditProject, ProjectQualityReport } from '../services/projectQuality';
import { synthesizeDesign } from '../services/aiDesignEngine';

const uid=(p:string)=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const dimensions:Dimensions={width_mm:800,height_mm:800,thickness_mm:12,relief_depth_mm:3.5,grout_joint_mm:2.5,edge_profile:'rectified_90',chamfer_width_mm:1};
const finish:FinishProps={roughness:.22,metallic:.08,glaze_type:'satin',luster_sheen:.55,subsurface_scatter:.25,bump_intensity:.7};
const primary='#1B365D', secondary='#D4AF37', accent='#F3EFE0';
const color:ColorData={primary_hex:primary,secondary_hex:secondary,accent_hex:accent,cmyk:hexToCmyk(primary),pantone_code:findClosestPantone(primary).code,pigment_names:[findClosestPantone(primary).pigment,'Calcined Kaolin Alumina','Synthetic Quartz Frit']};
const referenceAssets:ReferenceAssets={reference_image_url:null,ai_prompt:'High-end Carrara marble porcelain tile with geometric brushed brass waterjet inlay and micro-textured bas-relief',application_mode:'single_tile',floor_width_m:20,floor_length_m:10};
const material:MaterialDefinition={id:'mat_default',name:'Cadenza Porcelain / Carrara',color,finish,density_kg_m3:2400};
const vector=(id:string, layerId:string, points:any[], c:string, closed=true):SceneObject=>({id,name:id,kind:'vector_object',transform:{...IDENTITY_TRANSFORM_3D},visible:true,locked:false,manufacturingIncluded:true,layerId,materialId:material.id,geometry:{kind:'vector_object',params:{points,closed,type:'polyline',strokeWidth:2,depth_mm:2,color:c}}});
const base=(kind:ArchitecturalArchetype='flat_tile'):SceneObject=>({id:'object_primary',name:kind,kind,transform:{...IDENTITY_TRANSFORM_3D},visible:true,locked:false,manufacturingIncluded:true,layerId:'layer_base_body',materialId:material.id,geometry:kind==='flat_tile'?{kind,params:{dimensions}}:kind==='stair_tread'?{kind,params:{dimensions,stair:DEFAULT_STAIR_PARAMS}}:kind==='3d_wall_panel'?{kind,params:{dimensions,wallPanel:DEFAULT_WALL_PANEL_PARAMS}}:kind==='skirting_molding'?{kind,params:{dimensions,molding:DEFAULT_MOLDING_PARAMS}}:{kind,params:{dimensions,slab:DEFAULT_SLAB_PARAMS}}});
const stairDemo:SceneObject={id:'object_stair_demo',name:'Stair Tread Demo',kind:'stair_tread',transform:{...IDENTITY_TRANSFORM_3D,x_mm:1150,y_mm:0},visible:true,locked:false,manufacturingIncluded:true,layerId:'layer_base_body',materialId:material.id,geometry:{kind:'stair_tread',params:{dimensions:{...dimensions,width_mm:1200,height_mm:330,thickness_mm:20},stair:DEFAULT_STAIR_PARAMS}}};
const starter:SceneObject[]=[base('flat_tile'),stairDemo,vector('path_inlay_outer_diamond','layer_inlay',[{x:400,y:80},{x:720,y:400},{x:400,y:720},{x:80,y:400},{x:400,y:80}],secondary),vector('path_inlay_inner_medallion','layer_cut',[{x:400,y:280},{x:520,y:400},{x:400,y:520},{x:280,y:400},{x:400,y:280}],secondary),vector('path_engrave_fluting_1','layer_engrave',[{x:160,y:160},{x:640,y:640}],primary,false),vector('path_engrave_fluting_2','layer_engrave',[{x:640,y:160},{x:160,y:640}],primary,false)];
const calc=calculateMaterialMetrics(dimensions,20,10);
const emptyCam=runCAMQualityCheck([],dimensions,.75);

export interface SceneStoreState {
 projectId:string; projectName:string; createdAt:string; updatedAt:string; isDirty:boolean;
 activeSceneId:string; objects:Record<string,SceneObject>; objectIds:string[]; layers:ProjectLayer[]; materials:Record<string,MaterialDefinition>; activeLayerId:string; selectedObjectIds:string[]; activeObjectId:string|null;
 dimensions:Dimensions; finish:FinishProps; color:ColorData; referenceAssets:ReferenceAssets; productionMode:ProductionMode;
 activeArchetype:ArchitecturalArchetype; stairParams:StairTreadParams; wallPanelParams:WallPanel3DParams; moldingParams:SkirtingMoldingParams; slabParams:CountertopSlabParams;
 calculations:MaterialCalculations; camReport:CAMQualityReport; activePassport:FactoryPassport; manufacturingPlan:ManufacturingPlan; qualityReport:ProjectQualityReport;
 addObject:(o:SceneObject)=>void; removeObject:(id:string)=>void; setObjects:(o:SceneObject[])=>void; updateObjectTransform:(id:string,p:Partial<ObjectTransform3D>)=>void; selectObject:(id:string|null,opts?:{additive?:boolean})=>void; clearSelection:()=>void;
 toggleLayerVisibility:(id:string)=>void; toggleLayerLock:(id:string)=>void; setActiveLayer:(id:string)=>void; reorderLayers:(a:string,b:string)=>void; setLayerOpacity:(id:string,opacity:number)=>void; isLayerLocked:(id:string)=>boolean;
 setDimensions:(p:Partial<Dimensions>)=>void; setFinish:(p:Partial<FinishProps>)=>void; setPrimaryColor:(h:string)=>void; setSecondaryColor:(h:string)=>void; setAccentColor:(h:string)=>void; setReferenceAssets:(p:Partial<ReferenceAssets>)=>void; setReferenceImage:(u:string|null)=>void; setAiPrompt:(p:string)=>void; setApplicationMode:(m:ReferenceAssets['application_mode'])=>void; setProductionMode:(m:ProductionMode)=>void; setArchetype:(a:ArchitecturalArchetype)=>void; updateStairParams:(p:Partial<StairTreadParams>)=>void; updateWallPanelParams:(p:Partial<WallPanel3DParams>)=>void; updateMoldingParams:(p:Partial<SkirtingMoldingParams>)=>void; updateSlabParams:(p:Partial<CountertopSlabParams>)=>void;
 recomputeMetrics:()=>void; buildManufacturingPlan:()=>ManufacturingPlan; auditProject:()=>ProjectQualityReport; duplicateObject:(id:string)=>string|null; applyAIDesign:(prompt:string)=>void; buildProjectSnapshot:()=>ProjectV2; serializeProject:()=>string; downloadProject:()=>void; parseProjectFile:(j:string)=>any; loadProject:(p:any)=>void; newProject:()=>void; updatePassportStatus:(s:FactoryPassport['status'])=>void; setProjectName:(n:string)=>void;
}
function withMetrics(s:any){const vis=Object.values(s.objects as Record<string,SceneObject>).filter((o:any)=>o.manufacturingIncluded);return {calculations:calculateMaterialMetrics(s.dimensions,s.referenceAssets.floor_width_m,s.referenceAssets.floor_length_m),camReport:runCAMQualityCheck(vectorObjects(vis),s.dimensions,.75)}}
function vectorObjects(os:any[]):VectorPath[]{return os.filter(o=>o.kind==='vector_object').map(o=>({id:o.id,type:(o.geometry.params.type==='rectangle'||o.geometry.params.type==='circle'||o.geometry.params.type==='inlay_contour'||o.geometry.params.type==='relief_cut')?o.geometry.params.type:'polyline',points:o.geometry.params.points,color:o.geometry.params.color,closed:o.geometry.params.closed,layerId:o.layerId,strokeWidth:o.geometry.params.strokeWidth,depth_mm:o.geometry.params.depth_mm,transform:{x_mm:o.transform.x_mm,y_mm:o.transform.y_mm,rotation_deg:o.transform.rotation_z_deg,scale:o.transform.scale_x}} as VectorPath));}

export const useSceneStore=create<SceneStoreState>((set,get)=>({
 projectId:uid('proj'),projectName:'Untitled Cadenza Project',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),isDirty:false,activeSceneId:'scene_main',objects:Object.fromEntries(starter.map(o=>[o.id,o])),objectIds:starter.map(o=>o.id),layers:DEFAULT_LAYERS,materials:{[material.id]:material},activeLayerId:'layer_inlay',selectedObjectIds:[],activeObjectId:null,
 dimensions,finish,color,referenceAssets,productionMode:'waterjet_inlay',activeArchetype:'flat_tile',stairParams:DEFAULT_STAIR_PARAMS,wallPanelParams:DEFAULT_WALL_PANEL_PARAMS,moldingParams:DEFAULT_MOLDING_PARAMS,slabParams:DEFAULT_SLAB_PARAMS,calculations:calc,camReport:emptyCam,
 manufacturingPlan:buildManufacturingPlan(starter,dimensions,.75),qualityReport:{passed:true,score:100,errors:[],warnings:[],checks:{schema:true,scene:true,objectIndex:true,materials:true,geometry:true}},
 activePassport:{passport_id:`CAD-2026-${Math.floor(1000+Math.random()*9000)}-JED`,timestamp:new Date().toISOString(),designer_id:'ENG-LEAD-7842',target_factory_id:'SACMI-FAC-BOLOGNA-04',status:'qc_verified',dimensions,finish,color,production_mode:'waterjet_inlay',calculations:calc,cam_report:emptyCam,sync_token:uid('TOK')},
 addObject:o=>set(s=>({objects:{...s.objects,[o.id]:o},objectIds:[...s.objectIds,o.id],isDirty:true})),removeObject:id=>set(s=>{const o={...s.objects};delete o[id];return {objects:o,objectIds:s.objectIds.filter(x=>x!==id),selectedObjectIds:s.selectedObjectIds.filter(x=>x!==id),activeObjectId:s.activeObjectId===id?null:s.activeObjectId,isDirty:true}}),setObjects:os=>set({objects:Object.fromEntries(os.map(o=>[o.id,o])),objectIds:os.map(o=>o.id),selectedObjectIds:[],activeObjectId:null,isDirty:true}),updateObjectTransform:(id,p)=>set(s=>({objects:{...s.objects,[id]:{...s.objects[id],transform:{...s.objects[id].transform,...p}}},isDirty:true})),selectObject:(id,opts)=>{if(!id)return set({selectedObjectIds:[],activeObjectId:null});set(s=>opts?.additive?{selectedObjectIds:s.selectedObjectIds.includes(id)?s.selectedObjectIds.filter(x=>x!==id):[...s.selectedObjectIds,id],activeObjectId:id}:{selectedObjectIds:[id],activeObjectId:id})},clearSelection:()=>set({selectedObjectIds:[],activeObjectId:null}),
 toggleLayerVisibility:id=>set(s=>({layers:s.layers.map(l=>l.id===id?{...l,visible:!l.visible}:l),isDirty:true})),toggleLayerLock:id=>set(s=>({layers:s.layers.map(l=>l.id===id?{...l,locked:!l.locked}:l),isDirty:true})),setActiveLayer:id=>set({activeLayerId:id}),setLayerOpacity:(id,opacity)=>set(s=>({layers:s.layers.map(l=>l.id===id?{...l,opacity}:l),isDirty:true})),reorderLayers:(a,b)=>set(s=>{const l=[...s.layers],i=l.findIndex(x=>x.id===a),j=l.findIndex(x=>x.id===b);if(i<0||j<0)return s;const [x]=l.splice(i,1);l.splice(j,0,x);return {layers:l,isDirty:true}}),isLayerLocked:id=>get().layers.find(l=>l.id===id)?.locked??false,
 setDimensions:p=>set(s=>{const d={...s.dimensions,...p};const o=s.objects.object_primary;return {dimensions:d,objects:o?{...s.objects,object_primary:{...o,geometry:o.kind==='flat_tile'?{kind:'flat_tile',params:{dimensions:d}}:o.kind==='stair_tread'?{kind:'stair_tread',params:{dimensions:d,stair:s.stairParams}}:o.kind==='3d_wall_panel'?{kind:'3d_wall_panel',params:{dimensions:d,wallPanel:s.wallPanelParams}}:o.kind==='skirting_molding'?{kind:'skirting_molding',params:{dimensions:d,molding:s.moldingParams}}:{kind:'countertop_slab',params:{dimensions:d,slab:s.slabParams}}}}:s.objects,isDirty:true}}),setFinish:p=>set(s=>{const f={...s.finish,...p};const m={...s.materials.mat_default,finish:f};return {finish:f,materials:{...s.materials,mat_default:m},isDirty:true}}),setPrimaryColor:h=>set(s=>{const c=hexToCmyk(h),p=findClosestPantone(h),color={...s.color,primary_hex:h,cmyk:c,pantone_code:p.code,pigment_names:[p.pigment,...s.color.pigment_names.slice(1)]};return {color,materials:{...s.materials,mat_default:{...s.materials.mat_default,color}},isDirty:true}}),setSecondaryColor:h=>set(s=>{const color={...s.color,secondary_hex:h};return {color,materials:{...s.materials,mat_default:{...s.materials.mat_default,color}},isDirty:true}}),setAccentColor:h=>set(s=>{const color={...s.color,accent_hex:h};return {color,materials:{...s.materials,mat_default:{...s.materials.mat_default,color}},isDirty:true}}),setReferenceAssets:p=>set(s=>({referenceAssets:{...s.referenceAssets,...p},isDirty:true})),setReferenceImage:u=>set(s=>({referenceAssets:{...s.referenceAssets,reference_image_url:u},isDirty:true})),setAiPrompt:p=>set(s=>({referenceAssets:{...s.referenceAssets,ai_prompt:p},isDirty:true})),setApplicationMode:m=>set(s=>({referenceAssets:{...s.referenceAssets,application_mode:m},isDirty:true})),setProductionMode:m=>set(s=>({productionMode:m,isDirty:true})),
 setArchetype:a=>set(s=>{const d=a==='stair_tread'?{...s.dimensions,width_mm:1200,height_mm:330,thickness_mm:20}:a==='3d_wall_panel'?{...s.dimensions,width_mm:600,height_mm:1200,thickness_mm:12,relief_depth_mm:25}:a==='skirting_molding'?{...s.dimensions,width_mm:1200,height_mm:100,thickness_mm:18}:a==='countertop_slab'?{...s.dimensions,width_mm:3200,height_mm:1600,thickness_mm:20}:{...s.dimensions,width_mm:800,height_mm:800,thickness_mm:12}; const old=s.objects.object_primary; const o=old?{...old,name:a,kind:a,geometry:a==='flat_tile'?{kind:a,params:{dimensions:d}}:a==='stair_tread'?{kind:a,params:{dimensions:d,stair:s.stairParams}}:a==='3d_wall_panel'?{kind:a,params:{dimensions:d,wallPanel:s.wallPanelParams}}:a==='skirting_molding'?{kind:a,params:{dimensions:d,molding:s.moldingParams}}:{kind:a,params:{dimensions:d,slab:s.slabParams}}}:base(a);return {activeArchetype:a,dimensions:d,objects:{...s.objects,object_primary:o},isDirty:true}}),
 updateStairParams:p=>set(s=>{const stairParams={...s.stairParams,...p};const o=s.objects.object_primary;return {stairParams,objects:o&&o.kind==='stair_tread'?{...s.objects,object_primary:{...o,geometry:{kind:'stair_tread',params:{dimensions:s.dimensions,stair:stairParams}}}}:s.objects,isDirty:true}}),updateWallPanelParams:p=>set(s=>{const wallPanelParams={...s.wallPanelParams,...p};const o=s.objects.object_primary;return {wallPanelParams,objects:o&&o.kind==='3d_wall_panel'?{...s.objects,object_primary:{...o,geometry:{kind:'3d_wall_panel',params:{dimensions:s.dimensions,wallPanel:wallPanelParams}}}}:s.objects,isDirty:true}}),updateMoldingParams:p=>set(s=>{const moldingParams={...s.moldingParams,...p};const o=s.objects.object_primary;return {moldingParams,objects:o&&o.kind==='skirting_molding'?{...s.objects,object_primary:{...o,geometry:{kind:'skirting_molding',params:{dimensions:s.dimensions,molding:moldingParams}}}}:s.objects,isDirty:true}}),updateSlabParams:p=>set(s=>{const slabParams={...s.slabParams,...p};const o=s.objects.object_primary;return {slabParams,objects:o&&o.kind==='countertop_slab'?{...s.objects,object_primary:{...o,geometry:{kind:'countertop_slab',params:{dimensions:s.dimensions,slab:slabParams}}}}:s.objects,isDirty:true}}),
 recomputeMetrics:()=>set(s=>{const m=withMetrics(s);const manufacturingPlan=buildManufacturingPlan(Object.values(s.objects),s.dimensions,.75);const qualityReport=auditProject(s.buildProjectSnapshot());return {...m,manufacturingPlan,qualityReport,activePassport:{...s.activePassport,dimensions:s.dimensions,finish:s.finish,color:s.color,calculations:m.calculations,cam_report:m.camReport}}}),buildManufacturingPlan:()=>buildManufacturingPlan(Object.values(get().objects),get().dimensions,.75),auditProject:()=>auditProject(get().buildProjectSnapshot()),duplicateObject:id=>{const o=get().objects[id];if(!o)return null;const copy={...o,id:uid('obj'),name:`${o.name} Copy`,transform:{...o.transform,x_mm:o.transform.x_mm+Math.max(40,get().dimensions.width_mm*1.15)}};get().addObject(copy);get().selectObject(copy.id);return copy.id;},applyAIDesign:prompt=>{const s=get();const generated=synthesizeDesign(prompt,s.dimensions);const objects=generated.vectors.map(v=>vector(v.id,v.layer==='LAYER_CUT'?'layer_cut':v.layer==='LAYER_ENGRAVE'?'layer_engrave':'layer_inlay',v.points,v.color,v.closed));get().setObjects([...Object.values(s.objects).filter(o=>o.kind!=='vector_object'),...objects]);get().setAiPrompt(prompt);},
 buildProjectSnapshot:()=>{const s=get();const scene:SceneV2={id:s.activeSceneId,name:'Main Scene',objectIds:s.objectIds,objects:s.objects,layers:s.layers,materials:s.materials};return {schemaVersion:2,id:s.projectId,name:s.projectName,createdAt:s.createdAt,updatedAt:new Date().toISOString(),activeSceneId:s.activeSceneId,scenes:{[s.activeSceneId]:scene},referenceAssets:s.referenceAssets,manufacturing:{productionMode:s.productionMode,targetFactoryId:s.activePassport.target_factory_id},exportConfig:{lastExportedFormats:[],lastExportedAt:null}}},
 serializeProject:()=>JSON.stringify(get().buildProjectSnapshot(),null,2),downloadProject:()=>{const b=new Blob([get().serializeProject()],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=(get().projectName.replace(/[^a-z0-9-_]+/gi,'_')||'project')+'.cadenza.json';a.click();URL.revokeObjectURL(u);set({isDirty:false})},
 parseProjectFile:j=>{const p=JSON.parse(j);if(p.schemaVersion===2)return p;if(p.schemaVersion===1)return migrateV1(p);throw new Error('Unsupported Studio Cadenza schema.')},
 loadProject:p=>{const s=p.scenes[p.activeSceneId];if(!s)throw new Error('Project has no active scene.');set({projectId:p.id,projectName:p.name,createdAt:p.createdAt,updatedAt:p.updatedAt,activeSceneId:p.activeSceneId,objects:s.objects,objectIds:s.objectIds,layers:s.layers?.length?s.layers:DEFAULT_LAYERS,materials:s.materials||{mat_default:material},referenceAssets:p.referenceAssets,productionMode:p.manufacturing.productionMode,isDirty:false,selectedObjectIds:[],activeObjectId:null});get().recomputeMetrics()},
 setProjectName:n=>set({projectName:n,isDirty:true}),newProject:()=>set({projectId:uid('proj'),projectName:'Untitled Cadenza Project',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),objects:Object.fromEntries([base('flat_tile')].map(o=>[o.id,o])),objectIds:['object_primary'],layers:DEFAULT_LAYERS,materials:{[material.id]:material},selectedObjectIds:[],activeObjectId:null,isDirty:false}),updatePassportStatus:s=>set(st=>({activePassport:{...st.activePassport,status:s}}))
}));
function migrateV1(p:any):ProjectV2{const scene=p.scenes[p.activeSceneId]||Object.values(p.scenes||{})[0];const old=scene?.objects?.[scene?.objectIds?.[0]];if(!old)throw new Error('Invalid v1 project: missing primary object.');const objects:Record<string,SceneObject>={};const primary:SceneObject={id:old.id||'object_primary',name:old.name||old.archetype,kind:old.archetype,transform:{x_mm:old.transform?.x_mm||0,y_mm:old.transform?.y_mm||0,z_mm:0,rotation_x_deg:0,rotation_y_deg:0,rotation_z_deg:old.transform?.rotation_deg||0,scale_x:old.transform?.scale||1,scale_y:old.transform?.scale||1,scale_z:1},visible:true,locked:false,manufacturingIncluded:true,layerId:old.layerId||'layer_base_body',materialId:'mat_default',geometry:old.archetype==='flat_tile'?{kind:'flat_tile',params:{dimensions:old.dimensions}}:{kind:old.archetype,params:{dimensions:old.dimensions}} as any};objects[primary.id]=primary;(old.vectorPaths||[]).forEach((v:any)=>{objects[v.id]={id:v.id,name:v.id,kind:'vector_object',transform:{x_mm:v.transform?.x_mm||0,y_mm:v.transform?.y_mm||0,z_mm:0,rotation_x_deg:0,rotation_y_deg:0,rotation_z_deg:v.transform?.rotation_deg||0,scale_x:v.transform?.scale||1,scale_y:v.transform?.scale||1,scale_z:1},visible:true,locked:false,manufacturingIncluded:true,layerId:v.layerId||v.layer||'layer_inlay',materialId:'mat_default',geometry:{kind:'vector_object',params:{points:v.points,closed:v.closed,type:v.type,strokeWidth:v.strokeWidth,depth_mm:v.depth_mm,color:v.color}}}});return {schemaVersion:2,id:p.id,name:p.name,createdAt:p.createdAt,updatedAt:p.updatedAt||new Date().toISOString(),activeSceneId:p.activeSceneId||'scene_main',scenes:{[p.activeSceneId||'scene_main']:{id:p.activeSceneId||'scene_main',name:scene.name||'Main Scene',objectIds:Object.keys(objects),objects,layers:scene.layers||DEFAULT_LAYERS,materials:{mat_default:material}}},referenceAssets:p.referenceAssets||referenceAssets,manufacturing:p.manufacturing||{productionMode:'waterjet_inlay',targetFactoryId:'SACMI-FAC-BOLOGNA-04'},exportConfig:p.exportConfig||{lastExportedFormats:[],lastExportedAt:null}}}
